### ISSUE TITLE
Failsafer Random

### ISSUE THREAD

**Issue by indolering** [WebAssembly/wasi-random#1]
There are countless incidents where a platform subtly screws up their random number generator. Cryptographic protocol design now attempts to use things like the digest of the message being encrypted as a failsafe against a broken RNG.  WASI presents a unique opportunity to do something similar at the system level.

Off the top of my head:
1. WASI standard ~~salt~~ pepper. 
2. Incorporate the hash of the WASM binary.
3. Require callee to provide a salt, which a compiletime macro could then randomize.

Any WASI ~~salt~~ pepper would need to be a nothing-up-your-sleeve number.  Typically this is a mathematical constant.  Tau or picking the next Bitcoin block that ends in 42 after some pre-assigned date would be fun.

Edit: Even pepper is probably too strong of a word.  Keccak uses the term "customization string".

**Comment by sunfishcode** [comment]
In at least some use cases, the wasm binary won't be considered secret. With knowledge of the wasm binary, it would seem someone could predict 1, 2, and 3.

I don't have experience in this area. How big of a problem are broken RNGs these days? How practical is it to say that it's up to the WASI implementation to determine whether its platform's RNG is reliable, and to fix it if not?

**Comment by indolering** [comment]
> In at least some use cases, the wasm binary won't be considered secret.

Of course not, the point is to limit the damage done and increase the cost of nuisance attacks.  A static platform pepper forces an offline attacker to maintain a WASI specific set of precomputed rainbow tables.  Keying the output based on the binary or a program provided variable would protect users against casual or external adversaries who don't have complete information.

I'm also thinking about the situation where someone could use a simple counter to introduce non-reproducible behavior.  If we can get programmers to throw whatever input/state/entropy they control at the API, we can use a debug mode to negate those efforts.

**Comment by indolering** [comment]
This is largely an implementation detail, I can't think of anything useful that can be done at the platform/standard level.
