### ISSUE TITLE
Additional Input: Context

### ISSUE THREAD

**Issue by indolering** [WebAssembly/wasi-random#10]
Add optional failsafe mechanism variously known as a "personalization string" or "context variable" that concatenates static information to the seed.  This ensures that even if the entropy collector is totally borked and outputting all `0`s, the CSRNG output is still unique to each instance.  An attacker would have to not only know about the broken entropy collector, but also know the exact build and which `Random` instance generated the output.

Two ideas have emerged:

* Information that is unique to each isolate, like hashes obtained from code signing.
* Random bytes generated by the WASM compiler for each `Random` instance that is invisibly injected into the IR.

Sample (albeit slightly outdated) verbiage can be found [here](https://hackmd.io/@indo/SJv2uaXUu).

**Comment by sunfishcode** [comment]
This has similar considerations to #11, with the additional consideration that any information or hashes computed from code signing or the module itself could already be fed into the CSPRNG by the implementation, so my inclination here is not to include a context parameter in the API.
