### ISSUE TITLE
Additional Input: MSG

### ISSUE THREAD

**Issue by indolering** [WebAssembly/wasi-random#11]
Add optional failsafe mechanism most commonly referred to as "user input" or simply "entropy" that is concatenated to the seed when calling `getBytes` (`hash(seed+context+counter+msg)`) such that even if the CSRNG is totally broked, an attacker would need to know the exact callsite and runtime data supplied via `msg`.  For example, any application that requires the use of a nonce to encrypt a message can supply the message content itself.  

It is above my paygrade as to whether such data should be fed into the entropy collector as well, but I would err on the side of cautiousness.

Sample (albeit slightly outdated) verbiage and naming rationale can be found [here](https://hackmd.io/@indo/SJv2uaXUu).

**Comment by sunfishcode** [comment]
As we discussed offline, I can see how something like this would be useful in some settings, but just adding a parameter to the public API would encourage toolchains to add entropy to the main program or data. I think it would be better to add such facilities as custom sections, which caching tools could then be aware of, and distribution tools could even update with new seeds as needed, without having to dig into the program itself. As such, this would be best handled as a separate proposal.
