### ISSUE TITLE
Deprecate Non-Async Crypto Random API

### ISSUE THREAD

**Issue by indolering** [WebAssembly/wasi-random#2]
Blocking random APIs can cause timeouts and results in unpredictable program behavior during first boot.  The endless bikeshedding over Linux's rand vs urand could have been avoided by just providing an async function.

**Comment by sunfishcode** [comment]
Could you elaborate on how an async function would solve the problem? Do the programs that people are running when these kinds of scenarios occur typically have other work to do while they wait for the system to obtain sufficient entropy?

**Comment by indolering** [comment]
I'll document this here for future reference, but feel free to skip everything as I will explain it in our upcoming call.

[The problem with `/dev/random`](https://www.2uo.de/myths-about-urandom/) is that it is blocking, because it blocks based on the idea that entropy is a pool that can be drained.  This is incorrect, as the same logic would result in (for example) a GPG secret key being usable for only a limited number of messages.  This introduces DoS attack fuckery because unrelated programs can "drain" the entropy from `/dev/random`.  That's why the old standard advice is to just use `/dev/urandom`.

[The problem with `/dev/urandom/` ("unlimited random") is that it doesn't block](https://lwn.net/Articles/808575/), even if is has't been initialized (like during first boot). [In the past](https://lwn.net/Articles/658497/), it also meant that multiple threads all reading from `/dev/urandom/` might get the same bits of "random" output.  That's why the new standard advice is to use [getrandom](https://man7.org/linux/man-pages/man2/getrandom.2.html), whose blocking behavior can be parameterized.

And since non-deterministic/non-reproducible execution is a capability that might be denied, you want an API that can return multiple types of errors.  The most ergonomic way to structure control flow around a call that might take a long time or even fail is to use an async API that returns a result.

**Comment by indolering** [comment]
Probably not worth turning into async because (after the entropy has been built up) the call will no longer block and be very fast.  Even in scenarios where a process has to wait until entropy has been built up, WASI can kick those processes off the stack and run something else.  We also can't really revoke randomness/non-determinism later on, as any process with access to random bytes can create their own hash function.  As there will be no `stat_rand` or `unrandom`, the weight of having the `random` be incompatible with every other random is too high.
