### ISSUE TITLE
Make random_get require a capability

### ISSUE THREAD

**Issue by tschneidereit** [WebAssembly/wasi-random#6]
This was [brought up in a recent meeting](https://github.com/WebAssembly/WASI/blob/0e7c2c65b531f39b349d5e471acc8dd95ec81ae4/meetings/2019/WASI-11-07.md#make-clocksrandom-into-capabilities) after @sunfishcode [mentioned it in an issue](https://github.com/WebAssembly/WASI/issues/118#issuecomment-542948882), and @erights [filed an issue](https://github.com/bytecodealliance/wasmtime/issues/748) about it in the Wasmtime repo.

As Dan mentioned in the call on November 7, there's no mechanism yet for asking for such a capability.

@lukewagner, I think you had thoughts on mechanisms for these kinds of capabilities, too—around Interface Types, IIRC?

**Comment by erights** [comment]
See https://github.com/WebAssembly/wasi-classic-command/issues/4#issuecomment-794646793
