### ISSUE TITLE
Ban "pool" Terminology

### ISSUE THREAD

**Issue by indolering** [WebAssembly/wasi-random#7]
"Pools" are commonly used to describe filling up a fresh pool that is truly random and keeping consumers of randomness from using the same random numbers by creating independent pools that randomness is poured into.  However, the pool induces a mental model in which a pool is drained when used.

I propose describing the period of collecting entropy as an "initialization" phase that produces a seed.  Rotten seeds can and do occur, so we should replace them regularly.  But the exact timing of when that happens isn't important to the API consumer.  What's important is that a random numbers generated from the seed aren't used in a correlated fashion.  I would instead propose extending the "seed" metaphor to stalks and branches from which we cut off random numbers.

Feel free to close with an ACK if accepted.

**Comment by sunfishcode** [comment]
Can you describe the difference between a "drained pool" and a source for which reseeding is overdue?

Is it that the thing that determines whether reseeding is necessary is wall-clock time, rather than the amount of bytes read out of the device?

**Comment by indolering** [comment]
> Can you describe the difference between a "drained pool" and a source for which reseeding is overdue?

The "pool" terminology is an artifact of the implementation details of a CSRNG.  Advancements in CSRNG design are mostly clever ways to mitigate against broken or attacker controlled sources of entropy.  The details of how they collect and mix entropy from different sources fit the pool metaphor.  

But none of that is relevant to consumers of a CSRNG.  The CSRNG uses a hash function to hide its internal state/entropy/seed, limiting an attacker wishing to predict the output of the CSRNG to brute force methods.  As long as the CSRNG is using a seed ≥ 256 bits, the hash function remains unbroken, and P != NP ... it is physically impossible to brute force the seed's value.

Reseeding is thus never "overdue": if you *know* you have a good 256 bit seed (because you flipped a coin for ~5 minutes) and the seed is never exposed (because your RNG consists of you computing `SHA256(seed + counter)` using pencil and paper) then it would be safer to just use that _forever_.  But we need to hedge against things like a VM being restored from a saved state, which will reuse whatever seed was saved in memory.

> Is it that the thing that determines whether reseeding is necessary is wall-clock time, rather than the amount of bytes read out of the device?

Reseeding is determined by a bunch of rules of thumb balanced against performance concerns.  Wall clock time and volume of bytes read are both just ways of measuring usage and only impact reseeding tangentially.  For example, the Windows CSRNG reseeds a lot shortly after booting but slows down later based on the logic that entropy is low during the boot phase.


Sources:
* [Fortuna](https://www.schneier.com/wp-content/uploads/2015/12/fortuna.pdf)
* [Windows RNG whitepaper](https://www.microsoft.com/security/blog/2019/11/25/going-in-depth-on-the-windows-10-random-number-generation-infrastructure/)
* [RFC 4086 Randomness Requirements for Security](https://datatracker.ietf.org/doc/html/rfc4086)
* [DJB's Entropy Attacks!](http://blog.cr.yp.to/20140205-entropy.html)

**Comment by sunfishcode** [comment]
Thanks, that helps! I agree that we should avoid using "pool" terminology.
